{{ if .Values.gateway.multiMTls }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: istioinaction
  name: webapp-vs-from-gw
spec:
  hosts:
  - "webapp.istioinaction.io"
  gateways:
  - coolstore-gateway
  http:
  - route:
    - destination:
        host: webapp
        port:
          number: 80
  tls:
  - match:
    - port: 443
      sniHosts:
      - webapp.istioinaction.io
    route:
    - destination:
        host: webapp
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: istioinaction
  name: catalog-vs-from-gw
spec:
  hosts:
  - "catalog.istioinaction.io"
  gateways:
  - coolstore-gateway
  http:
  - route:
    - destination:
        host: catalog
        port:
          number: 80
  tls:
  - match:
    - port: 443
      sniHosts:
      - "catalog.istioinaction.io"
    route:
    - destination:
        host: catalog
        port:
          number: 80          
{{ end }}          