{{ if .Values.virtualService.requestRouting }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: istioinaction
  name: catalog-vs-from-gw
spec:
  hosts:
  - "catalog.istioinaction.io"
  gateways:
  - catalog-gateway
  http:
  - route:
    - destination:
        host: catalog
        subset: version-v2
    match:
    - headers:
        x-istio-cohort:
          exact: "internal"
  - route:
    - destination:
        host: catalog
        subset: version-v1
{{- end }}
