apiVersion: v1
kind: Pod
metadata:
  name: netshoot
  namespace: istioinaction
spec:
  containers:
  - name: netshoot
    image: nicolaka/netshoot
    command: ['sh', '-c', 'sleep 3600']
    env:
    - name: JWT_USER_TOKEN
      value: {{ .Values.jwt.userJwt }}
    - name: JWT_NOT_CONFIGURED_ISSUER
      value: {{ .Values.jwt.notConfiguredIssuer }}
